//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Education_Practic_num_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockView
    {
        public int Идентификатор_склада { get; set; }
        public Nullable<int> Количество_продуктов { get; set; }
        public System.DateTime Дата_поступления { get; set; }
        public string Наименование_продукта { get; set; }
    }
}
